/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventaris.view;

import inventaris.Gudang;
import inventaris.Orang;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelompok 8
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form AdminView
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnHapusPengguna = new javax.swing.JButton();
        txtUsernameKelola = new javax.swing.JTextField();
        btnEditPengguna = new javax.swing.JButton();
        txtPasswordKelola = new javax.swing.JTextField();
        btnSimpanPengguna = new javax.swing.JButton();
        cbPosisiKelola = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNamaAsliKelola = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPengguna = new javax.swing.JTable();
        spinIDPenggunaKelola = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        lblAdmin3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNamaGudang = new javax.swing.JTextField();
        simpanGudangButton = new javax.swing.JButton();
        editGudangButton = new javax.swing.JButton();
        hapusButtonGudang = new javax.swing.JButton();
        lblAdmin4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelGudang = new javax.swing.JTable();
        spinIDGudangKelola = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblAdmin2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        btnHapusPengguna.setText("HAPUS");

        btnEditPengguna.setText("EDIT");

        btnSimpanPengguna.setText("SIMPAN");

        cbPosisiKelola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penyedia", "Petugas" }));

        jLabel6.setText("Nama Asli");

        jLabel7.setText("Username");

        jLabel8.setText("Password");

        jLabel9.setText("Posisi");

        tabelPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelPengguna);

        jLabel11.setText("ID Pengguna");

        lblAdmin3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAdmin3.setText("Kelola Data Pengguna");
        lblAdmin3.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(lblAdmin3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaAsliKelola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsernameKelola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordKelola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPosisiKelola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinIDPenggunaKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusPengguna)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpanPengguna)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbPosisiKelola, spinIDPenggunaKelola, txtNamaAsliKelola, txtPasswordKelola, txtUsernameKelola});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAdmin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spinIDPenggunaKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaAsliKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsernameKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPosisiKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpanPengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditPengguna)
                    .addComponent(btnHapusPengguna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kelola Pengguna", jPanel2);

        jLabel10.setText("Nama Gudang");

        simpanGudangButton.setText("SIMPAN");

        editGudangButton.setText("EDIT");

        hapusButtonGudang.setText("HAPUS");

        lblAdmin4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAdmin4.setText("Kelola Data Pengguna");
        lblAdmin4.setToolTipText("");

        tabelGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelGudang);

        jLabel12.setText("ID Gudang");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanGudangButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(editGudangButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusButtonGudang)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(txtNamaGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinIDGudangKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAdmin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinIDGudangKelola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaGudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanGudangButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGudangButton)
                    .addComponent(hapusButtonGudang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Kelola Gudang", jPanel4);

        lblAdmin2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblAdmin2.setText("ADMIN");
        lblAdmin2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(lblAdmin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblAdmin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPengguna;
    private javax.swing.JButton btnHapusPengguna;
    private javax.swing.JButton btnSimpanPengguna;
    private javax.swing.JComboBox<String> cbPosisiKelola;
    private javax.swing.JButton editGudangButton;
    private javax.swing.JButton hapusButtonGudang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdmin2;
    private javax.swing.JLabel lblAdmin3;
    private javax.swing.JLabel lblAdmin4;
    private javax.swing.JButton simpanGudangButton;
    private javax.swing.JSpinner spinIDGudangKelola;
    private javax.swing.JSpinner spinIDPenggunaKelola;
    private javax.swing.JTable tabelGudang;
    private javax.swing.JTable tabelPengguna;
    private javax.swing.JTextField txtNamaAsliKelola;
    private javax.swing.JTextField txtNamaGudang;
    private javax.swing.JTextField txtPasswordKelola;
    private javax.swing.JTextField txtUsernameKelola;
    // End of variables declaration//GEN-END:variables

    //==================================================KELOLA PENGGUNA==============================================//
    public int getIDPenggunaKelola() {
        return (Integer) spinIDPenggunaKelola.getValue();
    }

    public String getNamaAsliKelola() {
        return txtNamaAsliKelola.getText();
    }

    public String getUsernameKelola() {
        return txtUsernameKelola.getText();
    }

    public String getPasswordKelola() {
        return txtPasswordKelola.getText();
    }

    public String getJenisPengguna() {
        return (String) cbPosisiKelola.getSelectedItem();
    }

    public void deactivateID() {
        spinIDPenggunaKelola.setEnabled(false);
    }

    public void activateID() {
        spinIDPenggunaKelola.setEnabled(true);
    }

    public void deactivateJenis() {
        cbPosisiKelola.setEnabled(false);
    }

    public void activateJenis() {
        cbPosisiKelola.setEnabled(true);
    }

    public boolean getIDStatus() {
        return spinIDPenggunaKelola.isEnabled();
    }

    public Object simpanButtonPressed() {
        return btnSimpanPengguna;
    }

    public Object editButtonPressed() {
        return btnEditPengguna;
    }

    public Object deleteButtonPressed() {
        return btnHapusPengguna;
    }

    public void setListOrang(ArrayList<Orang> list) {
        String[] judul = {"ID", "Nama", "Username", "Password", "Jenis User"};
        String[][] isi = new String[list.size()][5];
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i) instanceof inventaris.Penyedia) {
                isi[i][0] = String.valueOf(((inventaris.Penyedia) list.get(i)).getID());
            } else if (list.get(i) instanceof inventaris.Petugas) {
                isi[i][0] = String.valueOf(((inventaris.Petugas) list.get(i)).getIdPetugas());
            }
            isi[i][1] = list.get(i).getNama();
            isi[i][2] = list.get(i).getUsername();
            isi[i][3] = list.get(i).getPassword();
            if (list.get(i) instanceof inventaris.Penyedia) {
                isi[i][4] = "Penyedia";
            } else if (list.get(i) instanceof inventaris.Petugas) {
                isi[i][4] = "Petugas";
            }
        }
        DefaultTableModel tableModel = new DefaultTableModel(isi, judul);
        tabelPengguna.setModel(tableModel);
        tabelPengguna.getColumnModel().getColumn(0).setPreferredWidth(20);
    }

    public int getSelectedOrang() {
        return tabelPengguna.getSelectedRow();
    }

    public Object tabelOrangSelected() {
        return tabelPengguna;
    }

    public void refresh() {
        spinIDPenggunaKelola.setValue(0);
        txtNamaAsliKelola.setText("");
        txtUsernameKelola.setText("");
        txtPasswordKelola.setText("");
        cbPosisiKelola.setSelectedIndex(0);
    }

    public void refreshEdit(Orang b) {
        if (b instanceof inventaris.Penyedia) {
            spinIDPenggunaKelola.setValue(((inventaris.Penyedia) b).getID());
        } else if (b instanceof inventaris.Petugas) {
            spinIDPenggunaKelola.setValue(((inventaris.Petugas) b).getIdPetugas());
        }
        txtNamaAsliKelola.setText(b.getNama());
        txtUsernameKelola.setText(b.getUsername());
        txtPasswordKelola.setText(b.getPassword());
        if (b instanceof inventaris.Penyedia) {
            cbPosisiKelola.setSelectedIndex(0);
        } else if (b instanceof inventaris.Petugas) {
            cbPosisiKelola.setSelectedIndex(1);
        }
    }

    //=============================================END OF KELOLA PENGGUNA==========================================//
    //==================================================KELOLA GUDANG==============================================//
    public int getIDGudang() {
        return (Integer) spinIDGudangKelola.getValue();
    }

    public String getNamaGudangKelola() {
        return txtNamaGudang.getText();
    }

    public void deactivateIDGudang() {
        spinIDGudangKelola.setEnabled(false);
    }

    public void activateIDGudang() {
        spinIDGudangKelola.setEnabled(true);
    }

    public boolean getIDGudangStatus() {
        return spinIDGudangKelola.isEnabled();
    }

    public Object simpanBtnPressed() {
        return simpanGudangButton;
    }

    public Object editBtnPressed() {
        return editGudangButton;
    }

    public Object deleteBtnPressed() {
        return hapusButtonGudang;
    }

    public void setListGudang(ArrayList<Gudang> list) {
        String[] judul = {"ID", "Nama"};
        String[][] isi = new String[list.size()][2];
        for (int i = 0; i < list.size(); i++) {
            isi[i][0] = String.valueOf(((Gudang) list.get(i)).getID());
            isi[i][1] = list.get(i).getNama_gudang();
        }
        DefaultTableModel tableModel = new DefaultTableModel(isi, judul);
        tabelGudang.setModel(tableModel);
        tabelGudang.getColumnModel().getColumn(0).setPreferredWidth(20);
    }

    public int getSelectedGudang() {
        return tabelGudang.getSelectedRow();
    }

    public Object tabelGudangSelected() {
        return tabelGudang;
    }

    public void refreshGudang() {
        spinIDGudangKelola.setValue(0);
        txtNamaGudang.setText("");
    }

    public void refreshEditGudang(Gudang b) {
        spinIDGudangKelola.setValue(b.getID());
        txtNamaGudang.setText(b.getNama_gudang());
    }

    //=============================================END OF KELOLA GUDANG============================================//
    //====================================================FOR ALL==================================================//
    public void addListener(ActionListener e) {
        btnSimpanPengguna.addActionListener(e);
        btnEditPengguna.addActionListener(e);
        btnHapusPengguna.addActionListener(e);
        simpanGudangButton.addActionListener(e);
        editGudangButton.addActionListener(e);
        hapusButtonGudang.addActionListener(e);
    }

    public void addAdapter(MouseAdapter e) {
        tabelPengguna.addMouseListener(e);
        tabelGudang.addMouseListener(e);
    }

    //==================================================END OF FOR ALL=============================================//
}
